### ISSUE TITLE
16 - Filtro por Categoria

### ISSUE THREAD

**Issue by cassiosantana** [cassiosantana/blogstrap#27]
[Aula 16](https://youtu.be/3yQfEpwv_GA?list=PLqsayW8DhUmv49CBT7AvetMplBViAcwuk)

Primeiramente vamos fazer alterações no ArticlesController para limpar o código. Vamos utilizar a pasta
app/controllers/concerns ela serve para que possamos deixar códigos que podem ser utilizados posteriormente
por outros controllers. Nesta página vamos criar um arquivo chamado paginable.rb.

Nele vamos criar um módulo para adicionar o código.
```ruby
module Paginable
  protected

  def current_page
    (params[:page] || 1).to_i
  end
end
```
Remover a linha de código do controller de articles que faz este mesmo código.

Professor orienta como trocar a cor do botão(semanticamente)....

Vamos adicionar aos articles da página a sua categoria. Criar uma partial chamada _article_detail.html.erb
```erb
<%= month_day_comma_year(article.created_at) %> by
<%= article.user.email %> in
<%= article.category.name %>
```
Lembrando que neste caso o article é sem o '@' pois ele já chegará como parâmetro no momento que formos mandar
renderizar esta partial no show.

Vamos agora fazer a alteração em todos os elementos que exibem article que tem estas informações
adicionando o render:
```erb
  <p class="blog-post-meta">
    <%= render 'article_detail', article: @article  %>
  </p>
```

Continuação
https://youtu.be/3yQfEpwv_GA?list=PLqsayW8DhUmv49CBT7AvetMplBViAcwuk&t=858

Agora vamos fazer as categorias aparecerem no topnavbar listadas horizontalmente.

Adicionar um novo yield com o parâmetro :category_filter para servir de nome para ele.
  <% yield :category_filter %>

Agora o código das categorias serão adicionadas a uma div com esta :category_filter que justamente estará
apenas nas páginas que desejamos que aparecam que no caso é a index.

<%= content_for :category_filter do %>
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 link-secondary" href="#">World</a>
      <a class="p-2 link-secondary" href="#">U.S.</a>
      <a class="p-2 link-secondary" href="#">Technology</a>
      <a class="p-2 link-secondary" href="#">Design</a>
      <a class="p-2 link-secondary" href="#">Culture</a>
      <a class="p-2 link-secondary" href="#">Business</a>
      <a class="p-2 link-secondary" href="#">Politics</a>
      <a class="p-2 link-secondary" href="#">Opinion</a>
      <a class="p-2 link-secondary" href="#">Science</a>
      <a class="p-2 link-secondary" href="#">Health</a>
      <a class="p-2 link-secondary" href="#">Style</a>
      <a class="p-2 link-secondary" href="#">Travel</a>
    </nav>
  </div>
<% end %>

Assim mesmo tendo a tag yield na _topnavbar apenas aparecerá o conteúdo :category_filter na página index,
pois apenas nela existe este conteúdo.

Agora adicionar este código para aparecer os nomes das categorias e o link que passa para o index o parâmetro da
categorias para que o scope :filter_by_category faça seu trabalho passe para o index apenas os artigos da categoria
selecionada.

<%= content_for :category_filter do %>
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <% @categories.each do |category| %>
        <%= link_to category.name, root_path(category_id: category.id), class: "p-2 link-secondary" %>
      <% end %>
    </nav>
  </div>
<% end %>

A action index de articles também deve conchecer todas os artigos
```ruby
def index
  # adicionar esta linha no index de articles
  @categories = Category.sorted
end
```

Vamos agora fazer alteração visual para melhorar o destaque indo em app/assets/stylesheets/bootstrap_custom.scss e
adicionar:
```css
.category-active {
  font-weight: bold;
}

e adicionar ao código o if que define quando o css vai ser aplicado:
```erb
<%= content_for :category_filter do %>
  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <% @categories.each do |category| %>
        <%= link_to category.name, root_path(category_id: category.id),
                    class: "p-2 link-secondary #{'category-active' if category.id.to_s == params[:category_id]} " %>
      <% end %>
    </nav>
  </div>
<% end %>
```

Ao observar a url da página podemos ver que se algum filtro estiver aplicado, poderemos ver o nome dele como:
 ?category_id=5, por exemplo. Vamos corrigir isto pois não é correto.

Serão 3 alterações

- No index
```erb
        <%= link_to category.name, root_path(category: category.name),
                    class: "p-2 link-secondary #{'category-active' if category.name == params[:category]}" %>
```
- No model article
```ruby
  scope :filter_by_category, ->(category) { where category_id: category.id if category.present? }
```

- No index
```ruby
    category = Category.find_by_name(params[:category]) if params[:category].present?

    @highlights = Article.filter_by_category(category)
                         .descending_order
                         .first(3)

    @articles = Article.without_highlights(highlights_ids)
                       .filter_by_category(category)
                       .descending_order
                       .page(current_page)
```
